require('lv-globals')
vim.cmd('luafile ' .. CONFIG_PATH .. '/lv-settings.lua')
require('settings')
require('plugins')
require('lv-utils')
require('lv-autocommands')
require('keymappings')
require('colorscheme') -- This plugin must be required somewhere after nvimtree. Placing it before will break navigation keymappings
require('lv-galaxyline')
require('lv-telescope')
require('lv-treesitter')
require('lv-autopairs')
require('lv-which-key')


-- extras
if O.extras then
    require('lv-rnvimr')
    require('lv-gitblame')
    require('lv-matchup')
    require('lv-numb')
    require('lv-dial')
    require('lv-hop')
    require('lv-colorizer')
    require('lv-spectre')
    require('lv-symbols-outline')
    require('lv-vimtex')
    require('lv-zen')
    require('lv-dashboard')
    require('lv-lsp-rooter')
end

-- TODO is there a way to do this without vimscript
vim.cmd('source ' .. CONFIG_PATH .. '/vimscript/functions.vim')

-- LSP
--require('lsp')
require('lsp.java-ls')
require('lsp.angular-ls')
require('lsp.bash-ls')
require('lsp.clangd')
require('lsp.cmake-ls')
require('lsp.css-ls')
require('lsp.dart-ls')
require('lsp.docker-ls')
require('lsp.efm-general-ls')
require('lsp.elm-ls')
require('lsp.emmet-ls')
require('lsp.graphql-ls')
require('lsp.go-ls')
require('lsp.html-ls')
require('lsp.json-ls')
require('lsp.js-ts-ls')
require('lsp.kotlin-ls')
require('lsp.latex-ls')
require('lsp.lua-ls')
require('lsp.php-ls')
require('lsp.python-ls')
require('lsp.ruby-ls')
require('lsp.rust-ls')
require('lsp.svelte-ls')
require('lsp.terraform-ls')
-- require('lsp.tailwindcss-ls')
require('lsp.vim-ls')
require('lsp.vue-ls')
require('lsp.yaml-ls')
require('lsp.elixir-ls')
