#!/usr/bin/env bash

XDG_DATA_HOME="${XDG_DATA_HOME:-"$HOME/.local/share"}"
XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-"$HOME/.config"}"
XDG_CACHE_HOME="${XDG_CACHE_HOME:-"$HOME/.cache"}"

export LUNARVIM_RUNTIME_DIR="${LUNARVIM_RUNTIME_DIR:-"$XDG_DATA_HOME/lunarvim"}"
export LUNARVIM_CONFIG_DIR="${LUNARVIM_CONFIG_DIR:-"$XDG_CONFIG_HOME/lvim"}"
export LUNARVIM_CACHE_DIR="${LUNARVIM_CACHE_DIR:-"$XDG_CACHE_HOME/lvim"}"

ROOT_DIR=$(readlink -f "$(dirname "$(realpath "$0")")/..")
export LUNARVIM_BASE_DIR="${LUNARVIM_BASE_DIR:-$"$ROOT_DIR/CMAKE_INSTALL_DATAROOTDIR/lunarvim"}"

export NVIM_APPNAME="${NVIM_APPNAME:-"lvim"}"

exec nvim -u "$LUNARVIM_BASE_DIR/init.lua" "$@"
