name: General Issue
description: File a bug report
labels: [bug]

body:
  - type: markdown
    attributes:
      value: |
        _Before reporting:_ search [existing issues](https://github.com/lunarvim/lunarvim/issues?q=is%3Aissue+is%3Aopen+label%3Abug) and check the [Troubleshooting guide](https://www.lunarvim.org/troubleshooting). 
        If you need real-time help, join us on Discord. Thank you for helping us improve!

  - type: textarea
    id: problem-description
    attributes:
      label: Problem description
      description: Also tell us, what did you expect to happen?
      placeholder: |
        Steps to reproduce the behavior:
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: LunarVim version
      placeholder: |
        output of :LvimVersion
    validations:
      required: true
  - type: input
    id: nvim-version
    attributes:
      label: Neovim version (>= 0.7.2)
      description: "Output of `nvim --version`"
      placeholder: |
        NVIM v0.8.0-dev+199-g2875d45e7
    validations:
      required: true
  - type: input
    id: system-version
    attributes:
      label: "Operating system/version"
      placeholder: "macOS 11.5"
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: "Steps to reproduce"
      description: "Steps to reproduce using the minimal config."
      placeholder: |
        1. `nvim -u ~/.local/share/lunarvim/lvim/tests/minimal_lsp.lua`
        2. ...
  - type: textarea
    id: support-info
    attributes:
      label: support info
      description: Information from LspInfo and LvimInfo
      placeholder: |
        ```console
        # :LspInfo
        ```
        ```console
        # :LvimInfo
        ```
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem
