name: LSP Issue
description: File a bug report related to LSP (intellisense, completion, diagnostics, etc) 
labels: [bug, LSP]

body:
  - type: markdown
    attributes:
      value: |
        _Before reporting:_ search [existing issues](https://github.com/LunarVim/LunarVim/issues?q=is%3Aissue) (both open and closed) and check the [Troubleshooting guide](https://www.lunarvim.org/docs/troubleshooting).
        If you need real-time help, join us on Discord. Thank you for helping us improve!
  - type: textarea
    id: problem-description
    attributes:
      label: Problem description
      description: "A short description of the problem you are reporting."
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: LunarVim version
      description: "output of `:LvimVersion` (hold shift when selecting and copy using the terminal's copy binding)"
      placeholder: |
        branch-commit
    validations:
      required: true
  - type: input
    id: nvim-version
    attributes:
      label: Neovim version (>= 0.8.0)
      description: "Output of `nvim --version`"
      placeholder: |
        NVIM v0.8.0-dev+199-g2875d45e7
    validations:
      required: true
  - type: input
    id: system-version
    attributes:
      label: "Operating system/version"
      placeholder: "macOS 11.5"
    validations:
      required: true
  - type: input
    id: servers
    attributes:
      label: "Affected language servers"
      description: "If this issue is specific to one or more language servers, list them here. If not, write 'all'."
      placeholder: "tsserver"
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: "Steps to reproduce"
      description: "Steps to reproduce using the minimal config."
      placeholder: |
        1. `nvim -u ~/.local/share/lunarvim/lvim/tests/minimal_lsp.lua`
        2. ...
  - type: textarea
    id: behavior
    attributes:
      label: "Actual behavior"
      description: "Observed behavior."
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: "Expected behavior"
      description: "A description of the behavior you expected."
  - type: textarea
    id: support-info
    attributes:
      label: support info
      description: Information from LspInfo and LvimInfo
      placeholder: |
        ```console
        # :LspInfo
        ```
        ```console
        # :LvimInfo
        ```
    validations:
      required: true
  - type: textarea
    id: lsp-logs
    attributes:
      label: logs
      description: Please copy and paste any relevant log output (last lines form `<leader> L l L`). This will be automatically formatted into code, so no need for backticks.
      render: console
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem
      
